name: Create Release with Zip Archive

on: push

jobs:
  release:
    name: Create Release
    permissions: write-all # this is the FIX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare build structure
        run: |
          mkdir -p build_temp
          cp -r config build_temp/
          cp -r kubejs build_temp/
          cp -r pack.mcmeta build_temp/
          cp -r pack.png build_temp/
          mkdir -p build_temp/resourcepacks

          echo "📦 files to build:"
          ls -la build_temp/

      - name: Create resource pack zip
        run: |
          cd "resourcepacks/Community Russian Translations"
          zip -r ../../build_temp/resourcepacks/Community_RussianTranslations.zip .
          cd ../..

      - name: Create zip archive
        run: |
          cd build_temp
          zip -r -9 ../CommunityRussianTranslation.zip . -x '*.DS_Store'
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.1
          name: Русский перевод
          files: CommunityRussianTranslation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}